package mctech.q;

import io.netty.buffer.ByteBuf;
import java.util.Objects;
import mctech.g.b.a.o;
import mctech.g.b.a.p;
import mctech.g.b.a.r;
import mctech.g.b.a.s;
import mctech.g.b.a.t;
import mctech.g.b.a.u;
import mctech.g.b.a.v;
import mctech.g.b.a.w;
import mctech.g.b.a.x;
import mctech.g.b.a.y;
import mctech.q.d.f;
import mctech.q.d.g;
import mctech.q.d.h;
import mctech.q.d.i;
import mctech.q.d.j;
import mctech.q.d.k;
import mctech.q.d.l;
import mctech.q.d.m;
import mctech.q.d.n;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.network.protocol.common.custom.CustomPacketPayload;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
import net.neoforged.neoforge.network.handling.DirectionalPayloadHandler;
import net.neoforged.neoforge.network.registration.PayloadRegistrar;

/* JADX INFO: loaded from: mctech-frozen-2.1.3-client-RELEASE.jar:mctech/q/e.class */
@EventBusSubscriber
public class e {
    @SubscribeEvent
    public static void a(RegisterPayloadHandlersEvent registerPayloadHandlersEvent) {
        PayloadRegistrar payloadRegistrarRegistrar = registerPayloadHandlersEvent.registrar("1.0");
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.a.a.c.a.a, mctech.q.d.d.a.a.c.a.b, new DirectionalPayloadHandler(mctech.q.d.d.a.a.c::a, mctech.q.d.d.a.a.c::b));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.a.b.a.C0038a.a, mctech.q.d.d.a.b.a.C0038a.b, new DirectionalPayloadHandler(mctech.q.d.d.a.b.a::a, mctech.q.d.d.a.b.a::b));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.a.b.b.a.a, mctech.q.d.d.a.b.b.a.b, new DirectionalPayloadHandler(mctech.q.d.d.a.b.b::a, mctech.q.d.d.a.b.b::b));
        payloadRegistrarRegistrar.playBidirectional(mctech.q.d.a.c.b.a, mctech.q.d.a.c.b.b, new DirectionalPayloadHandler(mctech.q.d.a.c::a, mctech.q.d.a.c::b));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.a.b.c.a.a, mctech.q.d.d.a.b.c.a.b, new DirectionalPayloadHandler(mctech.q.d.d.a.b.c::a, mctech.q.d.d.a.b.c::b));
        payloadRegistrarRegistrar.playToServer(mctech.q.d.a.a.C0034a.a, mctech.q.d.a.a.C0034a.b, new DirectionalPayloadHandler(mctech.q.d.a.a::a, mctech.q.d.a.a::b));
        payloadRegistrarRegistrar.playToServer(mctech.q.d.a.b.a.a, mctech.q.d.a.b.a.b, new DirectionalPayloadHandler(mctech.q.d.a.b::a, mctech.q.d.a.b::b));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.a.a.d.a.a, mctech.q.d.d.a.a.d.a.b, new DirectionalPayloadHandler(mctech.q.d.d.a.a.d::a, mctech.q.d.d.a.a.d::b));
        payloadRegistrarRegistrar.playToServer(mctech.q.d.a.a.c.a.a, mctech.q.d.a.a.c.a.b, new DirectionalPayloadHandler(mctech.q.d.a.a.c::a, mctech.q.d.a.a.c::b));
        payloadRegistrarRegistrar.playBidirectional(mctech.q.d.b.b.a.a, mctech.q.d.b.b.a.b, new DirectionalPayloadHandler(mctech.q.d.b.b::a, mctech.q.d.b.b::a));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.a.a.a.C0037a.a, mctech.q.d.d.a.a.a.C0037a.b, new DirectionalPayloadHandler(mctech.q.d.d.a.a.a::a, mctech.q.d.d.a.a.a::b));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.a.a.b.a.a, mctech.q.d.d.a.a.b.a.b, new DirectionalPayloadHandler(mctech.q.d.d.a.a.b::a, mctech.q.d.d.a.a.b::b));
        payloadRegistrarRegistrar.playBidirectional(mctech.q.d.b.a.C0035a.a, mctech.q.d.b.a.C0035a.b, new DirectionalPayloadHandler(mctech.q.d.b.a::a, mctech.q.d.b.a::a));
        payloadRegistrarRegistrar.playToServer(mctech.q.d.d.a.C0036a.a, mctech.q.d.d.a.C0036a.b, new DirectionalPayloadHandler(mctech.q.d.d.a::a, mctech.q.d.d.a::b));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.d.b.a.a, mctech.q.d.d.b.a.b, new DirectionalPayloadHandler(mctech.q.d.d.b::a, mctech.q.d.d.b::b));
        payloadRegistrarRegistrar.playToClient(mctech.q.d.c.a.a, mctech.q.d.c.a.b, new DirectionalPayloadHandler(mctech.q.d.c.a::a, mctech.q.d.c.a::b));
        payloadRegistrarRegistrar.playToServer(mctech.q.d.a.a.b.a, mctech.q.d.a.a.b.b, new DirectionalPayloadHandler(mctech.q.d.a.a.b::a, mctech.q.d.a.a.b::b));
        payloadRegistrarRegistrar.playToServer(mctech.q.d.a.a.a.a, mctech.q.d.a.a.a.b, new DirectionalPayloadHandler(mctech.q.d.a.a.a::a, mctech.q.d.a.a.a::b));
        payloadRegistrarRegistrar.playToClient(i.a, i.b, i::a);
        payloadRegistrarRegistrar.playToClient(g.a, g.c, g::a);
        payloadRegistrarRegistrar.playToServer(mctech.q.d.a.a, mctech.q.d.a.b, mctech.q.d.a::a);
        payloadRegistrarRegistrar.playToServer(mctech.q.d.b.a, mctech.q.d.b.c, mctech.q.d.b::a);
        payloadRegistrarRegistrar.playToServer(mctech.q.d.c.a, mctech.q.d.c.b, mctech.q.d.c::a);
        payloadRegistrarRegistrar.playToClient(mctech.h.b.b.a, mctech.h.b.b.b, mctech.h.b.a::a);
        payloadRegistrarRegistrar.playToClient(h.a, h.b, h::a);
        payloadRegistrarRegistrar.playToClient(mctech.c.d.b.a, mctech.c.d.b.b, new DirectionalPayloadHandler(mctech.c.d::a, (v0, v1) -> {
            mctech.c.d.a(v0, v1);
        }));
        payloadRegistrarRegistrar.playToClient(mctech.c.d.a.a, mctech.c.d.a.b, new DirectionalPayloadHandler(mctech.c.d::a, (v0, v1) -> {
            mctech.c.d.a(v0, v1);
        }));
        payloadRegistrarRegistrar.playToClient(mctech.c.d.c.a, mctech.c.d.c.b, new DirectionalPayloadHandler(mctech.c.d::a, (v0, v1) -> {
            mctech.c.d.a(v0, v1);
        }));
        payloadRegistrarRegistrar.playToServer(mctech.q.d.d.a, mctech.q.d.d.b, mctech.q.d.d::a);
        payloadRegistrarRegistrar.playToServer(f.a, f.b, f::a);
        payloadRegistrarRegistrar.playToServer(mctech.q.d.e.a, mctech.q.d.e.b, mctech.q.d.e::a);
        payloadRegistrarRegistrar.playToClient(mctech.y.g.b.a, mctech.y.g.b.b, mctech.y.g.b::a);
        payloadRegistrarRegistrar.playToClient(mctech.y.g.c.a, mctech.y.g.c.b, mctech.y.g.c::a);
        payloadRegistrarRegistrar.playToClient(mctech.y.g.a.a, mctech.y.g.a.b, mctech.y.g.a::a);
        payloadRegistrarRegistrar.playBidirectional(n.a, n.b, new DirectionalPayloadHandler(n::a, n::b));
        payloadRegistrarRegistrar.playBidirectional(m.a, m.b, new DirectionalPayloadHandler(m::a, m::b));
        payloadRegistrarRegistrar.playBidirectional(l.a, l.b, new DirectionalPayloadHandler(l::a, l::b));
        payloadRegistrarRegistrar.playToClient(j.a, j.b, j::a);
        payloadRegistrarRegistrar.playToServer(k.a, k.b, k::a);
        CustomPacketPayload.Type<mctech.g.b.a.i> type = mctech.g.b.a.i.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.i> streamCodec = mctech.g.b.a.i.b;
        mctech.g.b.a.a aVarA = mctech.g.b.a.a.a();
        Objects.requireNonNull(aVarA);
        payloadRegistrarRegistrar.playToClient(type, streamCodec, aVarA::a);
        CustomPacketPayload.Type<mctech.g.b.a.j> type2 = mctech.g.b.a.j.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.j> streamCodec2 = mctech.g.b.a.j.b;
        mctech.g.b.a.a aVarA2 = mctech.g.b.a.a.a();
        Objects.requireNonNull(aVarA2);
        payloadRegistrarRegistrar.playToClient(type2, streamCodec2, aVarA2::a);
        CustomPacketPayload.Type<mctech.g.b.a.n> type3 = mctech.g.b.a.n.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.n> streamCodec3 = mctech.g.b.a.n.b;
        mctech.g.b.a.a aVarA3 = mctech.g.b.a.a.a();
        Objects.requireNonNull(aVarA3);
        payloadRegistrarRegistrar.playToClient(type3, streamCodec3, aVarA3::a);
        CustomPacketPayload.Type<mctech.g.b.a.d> type4 = mctech.g.b.a.d.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.d> streamCodec4 = mctech.g.b.a.d.b;
        mctech.g.b.a.l lVarA = mctech.g.b.a.l.a();
        Objects.requireNonNull(lVarA);
        payloadRegistrarRegistrar.playToServer(type4, streamCodec4, lVarA::a);
        CustomPacketPayload.Type<mctech.g.b.a.a.c> type5 = mctech.g.b.a.a.c.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.a.c> streamCodec5 = mctech.g.b.a.a.c.b;
        mctech.g.b.a.a aVarA4 = mctech.g.b.a.a.a();
        Objects.requireNonNull(aVarA4);
        payloadRegistrarRegistrar.playToClient(type5, streamCodec5, aVarA4::a);
        CustomPacketPayload.Type<mctech.g.b.a.a.k> type6 = mctech.g.b.a.a.k.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.a.k> streamCodec6 = mctech.g.b.a.a.k.b;
        mctech.g.b.a.l lVarA2 = mctech.g.b.a.l.a();
        Objects.requireNonNull(lVarA2);
        payloadRegistrarRegistrar.playToServer(type6, streamCodec6, lVarA2::a);
        CustomPacketPayload.Type<v> type7 = v.a;
        StreamCodec<RegistryFriendlyByteBuf, v> streamCodec7 = v.b;
        mctech.g.b.a.l lVarA3 = mctech.g.b.a.l.a();
        Objects.requireNonNull(lVarA3);
        payloadRegistrarRegistrar.playToServer(type7, streamCodec7, lVarA3::a);
        CustomPacketPayload.Type<w> type8 = w.a;
        StreamCodec<RegistryFriendlyByteBuf, w> streamCodec8 = w.b;
        mctech.g.b.a.l lVarA4 = mctech.g.b.a.l.a();
        Objects.requireNonNull(lVarA4);
        payloadRegistrarRegistrar.playToServer(type8, streamCodec8, lVarA4::a);
        CustomPacketPayload.Type<s> type9 = s.a;
        StreamCodec<ByteBuf, s> streamCodec9 = s.b;
        mctech.g.b.a.g gVarA = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA);
        payloadRegistrarRegistrar.playToServer(type9, streamCodec9, gVarA::a);
        CustomPacketPayload.Type<x> type10 = x.a;
        StreamCodec<ByteBuf, x> streamCodec10 = x.b;
        mctech.g.b.a.g gVarA2 = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA2);
        payloadRegistrarRegistrar.playToServer(type10, streamCodec10, gVarA2::a);
        CustomPacketPayload.Type<p> type11 = p.a;
        StreamCodec<ByteBuf, p> streamCodec11 = p.b;
        mctech.g.b.a.g gVarA3 = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA3);
        payloadRegistrarRegistrar.playToServer(type11, streamCodec11, gVarA3::a);
        CustomPacketPayload.Type<o> type12 = o.a;
        StreamCodec<ByteBuf, o> streamCodec12 = o.b;
        mctech.g.b.a.g gVarA4 = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA4);
        payloadRegistrarRegistrar.playToServer(type12, streamCodec12, gVarA4::a);
        CustomPacketPayload.Type<mctech.g.b.a.b> type13 = mctech.g.b.a.b.a;
        StreamCodec<ByteBuf, mctech.g.b.a.b> streamCodec13 = mctech.g.b.a.b.b;
        mctech.g.b.a.e eVarA = mctech.g.b.a.e.a();
        Objects.requireNonNull(eVarA);
        payloadRegistrarRegistrar.playToClient(type13, streamCodec13, eVarA::a);
        CustomPacketPayload.Type<mctech.g.b.a.c> type14 = mctech.g.b.a.c.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.c> streamCodec14 = mctech.g.b.a.c.b;
        mctech.g.b.a.e eVarA2 = mctech.g.b.a.e.a();
        Objects.requireNonNull(eVarA2);
        payloadRegistrarRegistrar.playToClient(type14, streamCodec14, eVarA2::a);
        CustomPacketPayload.Type<y> type15 = y.a;
        StreamCodec<RegistryFriendlyByteBuf, y> streamCodec15 = y.b;
        mctech.g.b.a.f fVarA = mctech.g.b.a.f.a();
        Objects.requireNonNull(fVarA);
        payloadRegistrarRegistrar.playBidirectional(type15, streamCodec15, fVarA::a);
        CustomPacketPayload.Type<t> type16 = t.a;
        StreamCodec<RegistryFriendlyByteBuf, t> streamCodec16 = t.b;
        mctech.g.b.a.g gVarA5 = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA5);
        payloadRegistrarRegistrar.playToServer(type16, streamCodec16, gVarA5::a);
        CustomPacketPayload.Type<mctech.g.b.a.m> type17 = mctech.g.b.a.m.a;
        StreamCodec<RegistryFriendlyByteBuf, mctech.g.b.a.m> streamCodec17 = mctech.g.b.a.m.b;
        mctech.g.b.a.g gVarA6 = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA6);
        payloadRegistrarRegistrar.playToServer(type17, streamCodec17, gVarA6::a);
        CustomPacketPayload.Type<u> type18 = u.a;
        StreamCodec<RegistryFriendlyByteBuf, u> streamCodec18 = u.b;
        mctech.g.b.a.g gVarA7 = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA7);
        payloadRegistrarRegistrar.playToServer(type18, streamCodec18, gVarA7::a);
        CustomPacketPayload.Type<r> type19 = r.a;
        StreamCodec<RegistryFriendlyByteBuf, r> streamCodec19 = r.b;
        mctech.g.b.a.g gVarA8 = mctech.g.b.a.g.a();
        Objects.requireNonNull(gVarA8);
        payloadRegistrarRegistrar.playToServer(type19, streamCodec19, gVarA8::a);
    }
}
