package mctech.init;

import com.mojang.blaze3d.vertex.DefaultVertexFormat;
import com.mojang.blaze3d.vertex.VertexFormat;
import mctech.MCTech;
import mctech.utils.c.h;
import net.minecraft.client.renderer.RenderStateShard;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.world.inventory.InventoryMenu;

/* JADX INFO: loaded from: mctech-frozen-2.1.3-client-RELEASE.jar:mctech/init/MCTechRenderTypes.class */
public class MCTechRenderTypes {
    public static final RenderType FLUID_RENDER = RenderType.create(MCTech.loc("fluid").toString(), DefaultVertexFormat.POSITION_COLOR_TEX_LIGHTMAP, VertexFormat.Mode.TRIANGLES, 131072, false, false, RenderType.CompositeState.builder().setTextureState(new RenderStateShard.TextureStateShard(InventoryMenu.BLOCK_ATLAS, false, false)).setShaderState(RenderStateShard.RENDERTYPE_TRANSLUCENT_SHADER).setLightmapState(RenderStateShard.LIGHTMAP).setTransparencyState(RenderStateShard.TRANSLUCENT_TRANSPARENCY).setOutputState(RenderStateShard.TRANSLUCENT_TARGET).createCompositeState(true));
    public static final RenderType POS_COLOR_TRANSLUCENT = RenderType.create(MCTech.loc("position_color").toString(), DefaultVertexFormat.POSITION_COLOR, VertexFormat.Mode.TRIANGLES, h.i, false, false, RenderType.CompositeState.builder().setShaderState(RenderStateShard.POSITION_COLOR_SHADER).setTransparencyState(RenderStateShard.TRANSLUCENT_TRANSPARENCY).setOutputState(RenderStateShard.TRANSLUCENT_TARGET).createCompositeState(true));
    public static final RenderType LASER_MAIN_BEAM = RenderType.create(MCTech.loc("laser_main").toString(), DefaultVertexFormat.POSITION_COLOR_TEX_LIGHTMAP, VertexFormat.Mode.QUADS, h.i, false, false, RenderType.CompositeState.builder().setTextureState(new RenderStateShard.TextureStateShard(MCTech.loc("textures/misc/laser2.png"), false, false)).setShaderState(RenderStateShard.ShaderStateShard.POSITION_COLOR_TEX_LIGHTMAP_SHADER).setLayeringState(RenderStateShard.VIEW_OFFSET_Z_LAYERING).setTransparencyState(RenderStateShard.TRANSLUCENT_TRANSPARENCY).setDepthTestState(RenderStateShard.LEQUAL_DEPTH_TEST).setCullState(RenderStateShard.NO_CULL).setLightmapState(RenderStateShard.NO_LIGHTMAP).setWriteMaskState(RenderStateShard.COLOR_DEPTH_WRITE).createCompositeState(false));
    public static final RenderType LASER_MAIN_ADDITIVE = RenderType.create(MCTech.loc("laser_addictive").toString(), DefaultVertexFormat.POSITION_COLOR_TEX_LIGHTMAP, VertexFormat.Mode.QUADS, h.i, false, false, RenderType.CompositeState.builder().setTextureState(new RenderStateShard.TextureStateShard(MCTech.loc("textures/misc/laser_glow.png"), false, false)).setShaderState(RenderStateShard.ShaderStateShard.POSITION_COLOR_TEX_LIGHTMAP_SHADER).setLayeringState(RenderStateShard.VIEW_OFFSET_Z_LAYERING).setTransparencyState(RenderStateShard.TRANSLUCENT_TRANSPARENCY).setDepthTestState(RenderStateShard.LEQUAL_DEPTH_TEST).setCullState(RenderStateShard.NO_CULL).setLightmapState(RenderStateShard.NO_LIGHTMAP).setWriteMaskState(RenderStateShard.COLOR_WRITE).createCompositeState(false));
    public static final RenderType LASER_MAIN_CORE = RenderType.create(MCTech.loc("laser_core").toString(), DefaultVertexFormat.POSITION_COLOR_TEX_LIGHTMAP, VertexFormat.Mode.QUADS, h.i, false, false, RenderType.CompositeState.builder().setTextureState(new RenderStateShard.TextureStateShard(MCTech.loc("textures/misc/laser.png"), false, false)).setShaderState(RenderStateShard.ShaderStateShard.POSITION_COLOR_TEX_LIGHTMAP_SHADER).setLayeringState(RenderStateShard.VIEW_OFFSET_Z_LAYERING).setTransparencyState(RenderStateShard.TRANSLUCENT_TRANSPARENCY).setDepthTestState(RenderStateShard.NO_DEPTH_TEST).setCullState(RenderStateShard.NO_CULL).setLightmapState(RenderStateShard.NO_LIGHTMAP).setWriteMaskState(RenderStateShard.COLOR_WRITE).createCompositeState(false));
}
